### ISSUE TITLE
Received messages are not displayed in the debug section

### ISSUE THREAD

**Issue by SIECLudo** [sarthou/CAS_SIEC#7]
The received messages are displayed in the bottom log, and they should be (for now) displayed in the debug section.

**Comment by sarthou** [comment]
Now when you send a message to the application, if the message start with a label, it will be displayed into the log textbox with the corresponding color.

Labels are : 
- **[ERR]**  : error (red)  
- **[WRN]** : warning (orange)  
- **[DBG]** : debug (blue)  
- **[CMD]** : commands (black)
